// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type List struct {
	ListID      int64
	ListName    string
	IconColor   string
	DateCreated time.Time
}

type TodoItem struct {
	ItemID      int64
	ListID      int64
	Content     string
	DateCreated time.Time
	IsDone      bool
}

type UserInfo struct {
	PasswordHash string
	DateCreated  time.Time
}
